language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
before_install:
 - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
 - chmod +x ala_common.sh
 - source ./ala_common.sh
 - ala_travis_grails_setup_env
script:
 - ala_travis_grails_build
env:
  global:
  - secure: efext9CJMTPIGWEP66teUj3IqqnkMU7fTNBOZjFJsVO6xXU9+0WAo7yR8ZsyOhWIVf2lrTPbzR8lFtYK/HJfBd54tDqXG/1wXLPYA2GyzFpl0jz2gzJR3nlGldEGXJxAnU0DTkTQJQXHp1kYHTTSF7NXhPvax0jXJ+vArtCImyzwvYjFCFSV7isuj1/9KUlJ4Bjwe4qd/v1Wuaree8FEh2Z5SeDoJwPJhWByl2nSLdSBKDVK8wqQm1ArC6Ra7PgP76r6dHhDA0FJKkGFFxHMFGXQyfgMXou4yUNftRtG4VBIJFkyHSNlsc3c7Q8hF+Xc3fANXB+V99z76F0LqyZkN4eufD79J4Eyh6gDJYg3frCF/H52ypUGBbsZV/S4cyTKaEbl+8B2kOofHb4W2HTjz9eulU7tjmT2WhlFHWDAexF6651QwyWsgTDmOb2pmdyuqj5qb8BrYt49sq0hTAC0JlHJpYYtfQpTtnPZPZtSIA5YIlsBcmvkpRYc/ylmPkeQczcXDpfDQgqeMNSxzgjGrblVNSidvUQjC9pcrFsjL7mC4g4RZ/ImquDfmOYN2gqM2dAycruhHcbEBC0VtMKF4Z5/b3v0RmZSwJ+sfYNptckoBfki0QvfZJWQ8DSmnbtRd3kkd6NZv2kfNxXac9KP4QSP75kWc/cRWLdhBva0hck=
  - secure: ED0LCg2J6ESbHclzjYgM/rCJTwE4lYrf3HoL7YNqV+hbprHY5inAkVRufhqAKHxnC0rzVVw9THDxOvhsWiPjob+UGYYCbPX4nabQzvURyQsdECPigSoCHIyFs5VwjGOANbovYVMIMe91gSRhMJTilCS+YUv/fWoAIy6BCvJ+p+91LKzmcVtZJqOVtdfSr1HvBzu+6QtpM9qkzCHExhePMtYPDHONxsWPrbI0Go0NgQJzEUiyOlksUDjkQBrH1Pmwbt4O8zV12gX56BNnvcrV5thJNiDANizGD1fCkgEWwmeagXTVsY8U0PkkHUOm/U8luhxgfXnec6/elE9dM5dGtvftohdA5dbixgT+tIq4THxjTirj4F1rvx+80TLNfCQ00GarCKVBysdrjlj+JLDqkaPVoOT5cfgNx4sOv1MkQj8MUnqwtCzW1xtePo35KhUI94OA1HxZx2KEJz0jdNDvufG525iMdYj09gg3bsyqhRor58zEdNfAnJEML10zpwMqSBwXpy6U4RKa7g/wEBklUyvH8QSGxX4Ir2ryRN2eHw/oJiq7AgBGm1uGFhXX8ARN1aKcZlcJTAWnp2iN5Wb7wMcMIjjiOp2DUEdPzS+FaaJEpZhXsnst6UYXs4DDpggzUlRuTZNL82iKvrrVMjMambsVWWtzj3Wwci9fAMNT300=
